apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-fbc-stage-index-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-fbc-stage-index-component
    app.kubernetes.io/part-of: e2e-fbc-stage-index-application
  name: e2e-fbc-stage-index-component
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: e2e-fbc-stage-index-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: e2e-fbc-stage-index-component
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/dev-release-team-tenant/e2e-fbc-stage-index-application/e2e-fbc-stage-index-component@sha256:4db7e7a008b1d45581abdcd93a8f299033006ab5cef8debc3d9295cbdfc543c0
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
